### ISSUE TITLE
Price change resume from last value

### ISSUE THREAD

**Issue by cicardia** [andrefbsantos/boilr#101]
After triggering, if you press resume, the alarm will probably keep triggering. Shouldn't it resume but use last value as the new reference?

I believe that's the logical behavior.

**Comment by dllud** [comment]
Nope, that way it wouldn't follow the sliding window definition. You have to compare with the price from Δt time ago, you cannot jump all of a sudden.

Note that it *usually* keeps triggering but that isn't always the case. Triggers will stop if price tendency changes direction.

**Comment by cicardia** [comment]
Thats for when you set the alarm. When you resume, it should Start counting from that moment. Otherwise it works like a ticker and not as an alarm.

**Comment by dllud** [comment]
> it should Start counting from that moment

That way you are not following the alarm semantic. Instead of comparing with the value from Δt time ago you will compare with the value from a few seconds ago, loosing all history,

This erroneous behaviour is exactly what we are forced to do during the alarm bootstrap. And you correctly criticized it, saying "there should be some server were we could fetch the history from Δt time ago".

Perhaps the resume button is not that useful, most of the time you will want to turn off the alarm, set a new change value and then turn it on.

**Comment by cicardia** [comment]
Then, the alarm is only useful if price has stabilized. Otherwise it keeps triggering. Resume would keep the same reference, reset would let you increse or decrease change. And then off?
