### ISSUE TITLE
Alarms not updating with low quality internet connection

### ISSUE THREAD

**Issue by cicardia** [andrefbsantos/boilr#51]
boilr had internet (other apps had it and i was browsing with NP) alarms didn't update for more than 30mins, I had them set to 1s. 30mins after, boom! btc price was up by $10 while boilr still hadn't updated...

this happened twice. I think it happens when I go somewhere where the connection might be weaker. the only way to solve this is to force stop boilr and relaunch it...

**Comment by dllud** [comment]
When internet connection is weak the AsyncTasks launched to fetch the last value from the exchanges block for at least 1 minute before they timeout. Therefore, on alarms with a short update interval, we ended up with a long queue of AsyncTasks which were causing troubles.
This should be fixed with 8fb9886445b643ada422e112b27d2801fe2ba2ab.
