### ISSUE TITLE
Alarm status bar notification should link to alarm settings

### ISSUE THREAD

**Issue by cicardia** [andrefbsantos/boilr#57]
when pressing the alarm notification we should be directed to the alarm's settings, instead of the alarm list

**Comment by andrefbsantos** [comment]
We are able to change the behavior of clicking in the notification to go to the alarm settings, but when you leave the alarm settings, you will exit Boilr instead of returning to the alarm list. This behavior comes from the stack nature of the activities. When you open an alarm setting from the alarm list you are placing the alarm setting on top of the alarm list and when you return, the stack just pops the alarm setting and returns to the alarm list. When you open the alarm setting from the notification, there is only an alarm setting in the stack, therefore after you exit the alarm settings, you will exit Boilr.
This can be fixed in conjunction with #48 and #49, when we upgrade the Android SDK.
