### ISSUE TITLE
Pinstripe coherence

### ISSUE THREAD

**Issue by cicardia** [andrefbsantos/boilr#68]
There's a pinstripe pattern behind the alarm list. Why not use it on the whole app backgrounds? Settings page, notification, triggered alarm, etc?
I'd say, leave android defaults as they are, just try being more coherent where there's the possibility.

**Comment by dllud** [comment]
We tried that and it becomes a mess. Not having the pinstripe on settings activities allows us to better distinguish them from the app main activity (the alarms' list). Notice that other apps that use pinstripe (Whatsapp, Telegram and Chat Secure) only use it in their main activity (the one which is displayed for longer).
Can you do some research on this?

I'll add the pinstripe to all activities and take some screenshots for us to compare.

**Comment by cicardia** [comment]
Hey, I'm confirming that the textured background is a main window exclusive on most apps.

I'd say to have the textured pinstripe as a background everywhere and then work with the alphas of the several elements. Just as we did for the main. Is this too troublesome? We should do this together, and in our native language. For speed sake!

**Comment by dllud** [comment]
Here go all the options.

- Light theme alarm list

![light-alarm-list](https://cloud.githubusercontent.com/assets/1716156/6281415/0ef38ca0-b8b9-11e4-9ae5-1c48c33585ee.png)
- Light theme settings with and without pinstripe

![light-settings-with-pinstripe](https://cloud.githubusercontent.com/assets/1716156/6281419/1edb148a-b8b9-11e4-9ba1-5bed0cf50fc9.png) ![light-settings-no-pinstripe](https://cloud.githubusercontent.com/assets/1716156/6281420/222a4f0c-b8b9-11e4-9abe-4fe8dfd0692c.png)

- Dark theme with Holo bar alarm list

![dark-holo-bar-alarm-list](https://cloud.githubusercontent.com/assets/1716156/6281434/50f82e44-b8b9-11e4-81f4-2d14c713742e.png)

- Dark theme with Holo bar settings with and without pinstripe

![dark-holo-bar-settings-with-pinstripe](https://cloud.githubusercontent.com/assets/1716156/6281440/62874442-b8b9-11e4-865d-aa86a3d17e7a.png) ![dark-holo-bar-settings-no-pinstripe](https://cloud.githubusercontent.com/assets/1716156/6281442/66125ba6-b8b9-11e4-8d4d-ac3a66337b56.png)

- Dark theme with Holo solid bar alarm list

![dark-solid-bar-alarm-list](https://cloud.githubusercontent.com/assets/1716156/6281443/7428efac-b8b9-11e4-830f-98110899ab09.png)

- Dark theme with Holo solid bar settings with and without pinstripe

![dark-solid-bar-settings-with-pinstripe](https://cloud.githubusercontent.com/assets/1716156/6281446/7f050924-b8b9-11e4-9a5a-0ebf5000da47.png) ![dark-solid-bar-settings-no-pinstripe](https://cloud.githubusercontent.com/assets/1716156/6281447/8218f102-b8b9-11e4-95d6-0567e0ebbd95.png)

**Comment by dllud** [comment]
I prefer without pinstripe for both themes and the dark theme with the regular (blue underlined) Holo bar,

On both I would decrease the alpha of the ON alarm row to make them more white/black.

**Comment by cicardia** [comment]
I prefer the normal holo bar too, but i'd leave settings with the pinstripe.

>On both I would decrease the alpha of the ON alarm row to make them more white/black.
do you mean decreasing the on alarm box alpha? wouldn't that make the background more visible?
i like it the way it is. wouldn't mind checking it out with different alphas.

**Comment by dllud** [comment]
Yes, I thought it would be better to have the alarm box background more visible, specially in dark theme, in order to get closer to the action bar colour. But I won't touch it because I am changing other things (read bellow).

I was getting annoyed by the settings lists with pinstripe, specially with the dark theme. Every time I opened them I thought "Why is this different from everything else in my system?".  I checked even more apps that use pinstripe (OsmAnd~ and Quickdic) and they all have the settings background in pure black. Then I opened [CMFileManager](https://github.com/CyanogenMod/android_packages_apps_CMFileManager) and there was my answer:

![cmfilemanager-dark](https://cloud.githubusercontent.com/assets/1716156/6283066/f2774814-b8d6-11e4-9dc6-c3e5161043bd.png) ![cmfilemanager-light](https://cloud.githubusercontent.com/assets/1716156/6283067/f27d3a12-b8d6-11e4-9055-c4c29f15c154.png)

You must use the pinstripe in the action bar too AND have the blue line separator for both dark and light themes. Now it looks good and coherent:

![dark-alarm-list](https://cloud.githubusercontent.com/assets/1716156/6283097/4a53dade-b8d7-11e4-9e2b-f6bc7cc66363.png) ![dark-settings](https://cloud.githubusercontent.com/assets/1716156/6283096/4a535d7a-b8d7-11e4-8340-674681c20ec1.png) ![dark-triggered-notification](https://cloud.githubusercontent.com/assets/1716156/6283095/4a525fb0-b8d7-11e4-9e25-527372106c9f.png)

![light-alarm-list](https://cloud.githubusercontent.com/assets/1716156/6283112/7650453c-b8d7-11e4-9496-e3a1be4fbdf3.png) ![light-settings](https://cloud.githubusercontent.com/assets/1716156/6283111/764de0b2-b8d7-11e4-98f6-7e3fe44e083f.png) ![light-triggered-notification](https://cloud.githubusercontent.com/assets/1716156/6283113/765080e2-b8d7-11e4-87ee-61a3ce020928.png)
